# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the application files to the container
COPY . .

# Install application dependencies
RUN pip install -r requirements.txt

# Expose port 5000
EXPOSE 5000

# Define the command to run the Flask application
CMD ["python", "app.py"]
